### PR TITLE
Fix issue with custom template http request

### PR DESCRIPTION
**Pull request by Marcrazyness**
Update to use the response.data which is the actual template vs the entire response when passing to processNotificationTemplate.

### CODE REVIEW

**Comment by vitorcamachoo** [comment]
+1

**Comment by alexcrack** [comment]
Please update production-built file for merging.

**Comment by Marcrazyness** [comment]
Hey @alexcrack, I am not sure which file you are referring to. Could you please be more specific?

**Comment by Marcrazyness** [comment]
Updated to include production built files.

**Comment by ben-codefresh** [comment]
@alexcrack any updates on when it going to be merged?

**Pull request merged**
