### PR TITLE
add onClick event notification

### PR DESCRIPTION
**Pull request by andradefil**
added event onclick because the callback from onClose event is called every time when the notification is closed, this new event added a callback only to click.

### CODE REVIEW

**Comment by runtheyards** [comment]
Take it this never made it into a release, would have been a useful feature as the onClose event seems to get called every time a notification dismisses itself. Would have been good to have something that can be used just for the click event.

**Comment by runtheyards** [comment]
Good ol' open source, valid changes sitting as PR for over a year. Guess this project is not maintained anymore.

**Comment by killboard** [comment]
Some PR's are from 2016

**Comment by ghost** [comment]
Thanks @alexcrack for accepting merge request and developing this library. Has served me well on my project.

**Pull request merged**
